# Generated by Django 5.1.3 on 2024-12-10 18:42

import choices.choices
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vaga', models.CharField(max_length=100)),
                ('faixa_salarial', models.CharField(choices=choices.choices.get_faixa_salarial_choices, max_length=5)),
                ('escolaridade', models.CharField(choices=choices.choices.get_escolaridade_choices, max_length=18)),
                ('requisitos', models.TextField()),
                ('empresa', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)
                ),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_salarial', models.CharField(choices=choices.choices.get_faixa_salarial_choices, max_length=5)),
                ('escolaridade', models.CharField(choices=choices.choices.get_escolaridade_choices, max_length=18)),
                ('experiencia', models.TextField()),
                ('email', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vagas', models.ManyToManyField(to='vagas.vaga')),
            ],
        ),
    ]
