# Generated by Django 5.1.3 on 2024-12-05 17:38

import choices.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_salarial', models.CharField(choices=choices.choices.get_faixa_salarial_choices, max_length=5)),
                ('escolaridade', models.CharField(choices=choices.choices.get_escolaridade_choices, max_length=18)),
                ('experiencia', models.TextField()),
            ],
        ),
    ]
