# Generated by Django 5.1.3 on 2024-12-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='vagas',
            new_name='vaga',
        ),
    ]
