# Generated by Django 5.1.2 on 2024-10-14 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('faixa_salarial', models.CharField(choices=[('ATÉ 1.000', 'Até 1.000'), ('DE 1.000 A 2.000', 'De 1.000 a 2.000'), ('DE 2.000 A 3.000', 'De 2.000 a 3.000'), ('ACIMA DE 3.000', 'Acima de 3.000')], max_length=16)),
                ('requisitos', models.TextField()),
                ('escolaridade_minima', models.CharField(choices=[('FUNDAMENTAL', 'Ensino fundamental'), ('MEDIO', 'Ensino médio'), ('TECNOLOGO', 'Tecnólogo'), ('SUPERIOR', 'Ensino Superior'), ('POS', 'Pós / MBA / Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=11)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(limit_choices_to={'is_company': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('pretensao_salarial', models.CharField(choices=[('ATÉ 1.000', 'Até 1.000'), ('DE 1.000 A 2.000', 'De 1.000 a 2.000'), ('DE 2.000 A 3.000', 'De 2.000 a 3.000'), ('ACIMA DE 3.000', 'Acima de 3.000')], max_length=16)),
                ('experiencia', models.TextField()),
                ('ultima_escolaridade', models.CharField(choices=[('FUNDAMENTAL', 'Ensino fundamental'), ('MEDIO', 'Ensino médio'), ('TECNOLOGO', 'Tecnólogo'), ('SUPERIOR', 'Ensino Superior'), ('POS', 'Pós / MBA / Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=11)),
                ('candidato', models.ForeignKey(limit_choices_to={'is_company': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='vaga.vaga')),
            ],
        ),
    ]
