name: Django CI

on:
  push: # Aciona em todos os push
  pull_request:
    branches: [ "main" ] # Aciona em PRs para a branch main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: false
        virtualenvs-path: ~/.cache/pypoetry/virtualenvs

    - name: Install Dependencies
      run: poetry install --with dev

    - name: Run Ruff Linter
      run: poetry run ruff check

    - name: Run Tests
      run: poetry run pytest . -v
